---
title: "Interactive Histogram"
output: slidy_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Static Histogram

The `hist` function allows us to easily create histograms:

```{r static_histogram}
hist(rnorm(100))
```


## Interactive Histogram with Shiny

This shiny app allows us to modify the dataset visualised in our histogram

```{r interactive_histogram}
library(shiny)
shinyApp(
  ui = fluidPage(
    sliderInput("no_data", label = "Number of data",
                min = 1000,
                max = 5000,
                value = 1000),
    sliderInput("mean", label = "Mean",
                min = 0,
                max = 8,
                value = 3),
    sliderInput("sd", label = "Standard Deviation",
                min = 1,
                max = 10,
                value = 2),
    uiOutput("xlim_ui"),
    plotOutput("histogram")
  ),
  server = function(input, output){
    
    output$xlim_ui <- renderUI({
      
      if(is.null(input$mean)){
        return()
      }
      
      sliderInput("xlim", label = "xlim",
                  min = input$mean,
                  max = 10,
                  value = input$mean,
                  step = 1)
    })
    
    output$histogram <- renderPlot({
      if(is.null(input$xlim)){
        return()
      }
      hist(rnorm(input$no_data, mean = input$mean, sd = input$sd), xlim = c(-input$xlim,input$xlim))
    })
  }
)
```
